title: My learning experience blog
author: Mike Banks
email: bishop.fadius@gmail.com
theme: minima
description: > # this means to ignore newlines until "baseurl:"
  This blog will be used to describe my learning experieince using GitHub.

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  mcbanks12 # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
